package entity;
// Generated 2019-3-19 22:57:03 by Hibernate Tools 5.2.11.Final

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Processactivityinvokingapplication.
 * @see entity.Processactivityinvokingapplication
 * @author Hibernate Tools
 */
@Stateless
public class ProcessactivityinvokingapplicationHome {

	private static final Log log = LogFactory.getLog(ProcessactivityinvokingapplicationHome.class);

	@PersistenceContext
	private EntityManager entityManager;

	public void persist(Processactivityinvokingapplication transientInstance) {
		log.debug("persisting Processactivityinvokingapplication instance");
		try {
			entityManager.persist(transientInstance);
			log.debug("persist successful");
		} catch (RuntimeException re) {
			log.error("persist failed", re);
			throw re;
		}
	}

	public void remove(Processactivityinvokingapplication persistentInstance) {
		log.debug("removing Processactivityinvokingapplication instance");
		try {
			entityManager.remove(persistentInstance);
			log.debug("remove successful");
		} catch (RuntimeException re) {
			log.error("remove failed", re);
			throw re;
		}
	}

	public Processactivityinvokingapplication merge(Processactivityinvokingapplication detachedInstance) {
		log.debug("merging Processactivityinvokingapplication instance");
		try {
			Processactivityinvokingapplication result = entityManager.merge(detachedInstance);
			log.debug("merge successful");
			return result;
		} catch (RuntimeException re) {
			log.error("merge failed", re);
			throw re;
		}
	}

	public Processactivityinvokingapplication findById(Integer id) {
		log.debug("getting Processactivityinvokingapplication instance with id: " + id);
		try {
			Processactivityinvokingapplication instance = entityManager.find(Processactivityinvokingapplication.class,
					id);
			log.debug("get successful");
			return instance;
		} catch (RuntimeException re) {
			log.error("get failed", re);
			throw re;
		}
	}
}
