package com.winginrian.hibernate.entity;
// Generated 2019-3-19 23:02:59 by Hibernate Tools 5.2.11.Final


import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Caseobject.
 * @see com.winginrian.hibernate.entity.Caseobject
 * @author Hibernate Tools
 */
@Stateless
public class CaseobjectHome {

    private static final Log log = LogFactory.getLog(CaseobjectHome.class);

    @PersistenceContext private EntityManager entityManager;
    
    public void persist(Caseobject transientInstance) {
        log.debug("persisting Caseobject instance");
        try {
            entityManager.persist(transientInstance);
            log.debug("persist successful");
        }
        catch (RuntimeException re) {
            log.error("persist failed", re);
            throw re;
        }
    }
    
    public void remove(Caseobject persistentInstance) {
        log.debug("removing Caseobject instance");
        try {
            entityManager.remove(persistentInstance);
            log.debug("remove successful");
        }
        catch (RuntimeException re) {
            log.error("remove failed", re);
            throw re;
        }
    }
    
    public Caseobject merge(Caseobject detachedInstance) {
        log.debug("merging Caseobject instance");
        try {
            Caseobject result = entityManager.merge(detachedInstance);
            log.debug("merge successful");
            return result;
        }
        catch (RuntimeException re) {
            log.error("merge failed", re);
            throw re;
        }
    }
    
    public Caseobject findById( Integer id) {
        log.debug("getting Caseobject instance with id: " + id);
        try {
            Caseobject instance = entityManager.find(Caseobject.class, id);
            log.debug("get successful");
            return instance;
        }
        catch (RuntimeException re) {
            log.error("get failed", re);
            throw re;
        }
    }
}

